service:
  name: hello-custom-authorizer

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2

functions:
  login:
    handler: handler.login
    events:
      - http:
          method: post
          path: login
  auth:
    handler: handler.auth
  hello1:
    handler: handler.hello1
    events:
      - http:
          method: get
          path: hello1
          authorizer: auth
  hello2:
    handler: handler.hello2
    events:
      - http:
          method: get
          path: hello2
          authorizer: auth
  hello3:
    handler: handler.hello3
    events:
      - http:
          method: get
          path: hello3
          authorizer: auth
